INSTALLED_APPS = [
    "daphne",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "rest_framework_simplejwt",
    "rest_framework_simplejwt.token_blacklist",
    "corsheaders",
    "djresttoolkit",
    "apps.accounts.apps.AccountsConfig",
    "apps.google_auth.apps.GoogleAuthConfig",
    "apps.health.apps.HealthConfig",
]
